### ISSUE TITLE
Project reference vs Include reference File

### ISSUE THREAD

**Issue by Yitzchok** [AutoMapper/AutoMapper.Extensions.OData#85]
Is there a reason not to have one project with all the shared code and add a project reference from the provider-specific code like EF and EFCore?

**Comment by BlaiseD** [comment]
It may be possible to use a single project.  On the other hand the namespace `Microsoft.AspNet.OData.Query` is used by both `Microsoft.AspNetCore.OData` and `Microsoft.AspNet.OData` assemblies i.e. we can share the code file because of the namespace but the referenced assemblies have to  be different.
