### ISSUE TITLE
[Question] Support for NET 5.

### ISSUE THREAD

**Issue by DanielGlos** [AutoMapper/AutoMapper.Extensions.OData#89]
Are you planning to support .NET 5? I know that the Microsoft.AspNetCore.OData package V8.0.0 supporting .NET 5 is still only in preview but I'm interested if you are working on this? My problem is that when I update this Microsoft.AspNetCore.OData to preview version namespace for ODataQueryOptions changes.

**Comment by BlaiseD** [comment]
Sounds like you're asking about [Microsoft.AspMetCore.OData v8 ](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/e5c3e496309c27ced1055b5405bca74488d44e0e/AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj#L23) (no maximum version set) rather than Net 5?  The package  supports  [.Net Standard 2.0](https://github.com/AutoMapper/AutoMapper.Extensions.OData/blob/e5c3e496309c27ced1055b5405bca74488d44e0e/AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj#L4) so .Net 5 is supported.

I'm not working on it to answer your question.  If  you've run into breaking changes upgrading to v8 then please open and issue or PR describing the problem.

Thanks.
